### ISSUE TITLE
line 2666 pos 12: '!_debugDisposed': is not true.

### ISSUE THREAD

**Issue by desmeit** [hekhy/testing_project#1]
Hello,

did you solve the issue with FixedExtentScrollController?
I have the same problem.
First click it is okay, second click I get the error.

**Comment by hekhy** [comment]
Yes, what I had to do was create the FixedExtentScrollController inside the widget where it is used like this every time that widget was built a new one was generated. Otherwise, if you create it globally, what happens is that when you use it the first time the FixedExtentScrollController starts and everything works fine, but the second time it is already deleted and that is why it no longer works.

I don't know if the error you receive is the same, but [here](https://github.com/hekhy/testing_project) is the link to the github repository that I create to test the error. The application is simply a main screen where some buttons that represent timers are shown and in the appbar you have the add button to enter NewTimerPage and from there select the day of the timer and save it.
If you try it as it is in the repository, the first time you create a timer everything will work fine, but the second time you want to create another timer, the error you have happens. To fix it simply as I said before you have to go to new_timer_page.dart and remove the line where the FixedExtentScrollController is from its current place and put it in the _NewTimerPageState so that it looks like this:

```
List<Widget> timers = [];
List<String> monthDays = List.generate(30, (index) => '${index + 1}');

class NewTimerPage extends StatefulWidget {
  const NewTimerPage({Key? key}) : super(key: key);

  @override
  _NewTimerPageState createState() => _NewTimerPageState();
}

class _NewTimerPageState extends State<NewTimerPage> {
  final FixedExtentScrollController controller = FixedExtentScrollController();

  @override
  Widget build(BuildContext context) {
```

It should work fine by now, hope this helps you.
